CREATE TABLE events (
    event_id SERIAL PRIMARY KEY,
    time DECIMAL NOT NULL,
    type VARCHAR(255) NOT NULL,
    person VARCHAR(255),
	link VARCHAR(255),
	actType VARCHAR(255),
	legMode VARCHAR(255),
    vehicle VARCHAR(255),
    networkMode VARCHAR(255),
    distance DECIMAL,
	mode VARCHAR(255),
    x_coordinate DECIMAL,
    y_coordinate DECIMAL,
    amount DECIMAL,
    purpose VARCHAR(255),
	transactionPartner VARCHAR(255),
	dvrpVehicle VARCHAR(255),
	taskType VARCHAR(255),
	taskIndex INT,
    dvrpMode VARCHAR(255),
	relativePosition DECIMAL,
	atStop Decimal,
	destinationStop VARCHAR(255),
    agent VARCHAR(255),
    facility VARCHAR(255),
    delay INT,
	vehicleID VARCHAR(255),
	transitRouteId VARCHAR(255),
	departureId VARCHAR(255),
	transitLineId VARCHAR(255),
	driverId VARCHAR(255),
	request VARCHAR(255)
);
end;